// soc_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_0 (
		input  wire        pll_0_outclk0_clk,                                 //                               pll_0_outclk0.clk
		input  wire        CIC_collector_0_reset_reset_bridge_in_reset_reset, // CIC_collector_0_reset_reset_bridge_in_reset.reset
		input  wire [16:0] CIC_collector_0_avalon_master_address,             //               CIC_collector_0_avalon_master.address
		output wire        CIC_collector_0_avalon_master_waitrequest,         //                                            .waitrequest
		input  wire        CIC_collector_0_avalon_master_chipselect,          //                                            .chipselect
		input  wire        CIC_collector_0_avalon_master_write,               //                                            .write
		input  wire [15:0] CIC_collector_0_avalon_master_writedata,           //                                            .writedata
		output wire [14:0] onchip_memory2_adc_a_s2_address,                   //                     onchip_memory2_adc_a_s2.address
		output wire        onchip_memory2_adc_a_s2_write,                     //                                            .write
		input  wire [15:0] onchip_memory2_adc_a_s2_readdata,                  //                                            .readdata
		output wire [15:0] onchip_memory2_adc_a_s2_writedata,                 //                                            .writedata
		output wire [1:0]  onchip_memory2_adc_a_s2_byteenable,                //                                            .byteenable
		output wire        onchip_memory2_adc_a_s2_chipselect,                //                                            .chipselect
		output wire        onchip_memory2_adc_a_s2_clken                      //                                            .clken
	);

	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // onchip_memory2_adc_a_s2_translator:uav_waitrequest -> CIC_collector_0_avalon_master_translator:uav_waitrequest
	wire  [15:0] cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdata;      // onchip_memory2_adc_a_s2_translator:uav_readdata -> CIC_collector_0_avalon_master_translator:uav_readdata
	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // CIC_collector_0_avalon_master_translator:uav_debugaccess -> onchip_memory2_adc_a_s2_translator:uav_debugaccess
	wire  [16:0] cic_collector_0_avalon_master_translator_avalon_universal_master_0_address;       // CIC_collector_0_avalon_master_translator:uav_address -> onchip_memory2_adc_a_s2_translator:uav_address
	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_read;          // CIC_collector_0_avalon_master_translator:uav_read -> onchip_memory2_adc_a_s2_translator:uav_read
	wire   [1:0] cic_collector_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // CIC_collector_0_avalon_master_translator:uav_byteenable -> onchip_memory2_adc_a_s2_translator:uav_byteenable
	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // onchip_memory2_adc_a_s2_translator:uav_readdatavalid -> CIC_collector_0_avalon_master_translator:uav_readdatavalid
	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_lock;          // CIC_collector_0_avalon_master_translator:uav_lock -> onchip_memory2_adc_a_s2_translator:uav_lock
	wire         cic_collector_0_avalon_master_translator_avalon_universal_master_0_write;         // CIC_collector_0_avalon_master_translator:uav_write -> onchip_memory2_adc_a_s2_translator:uav_write
	wire  [15:0] cic_collector_0_avalon_master_translator_avalon_universal_master_0_writedata;     // CIC_collector_0_avalon_master_translator:uav_writedata -> onchip_memory2_adc_a_s2_translator:uav_writedata
	wire   [1:0] cic_collector_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // CIC_collector_0_avalon_master_translator:uav_burstcount -> onchip_memory2_adc_a_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (17),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (17),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) cic_collector_0_avalon_master_translator (
		.clk                    (pll_0_outclk0_clk),                                                                //                       clk.clk
		.reset                  (CIC_collector_0_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (cic_collector_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (cic_collector_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (cic_collector_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (cic_collector_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (cic_collector_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (cic_collector_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (cic_collector_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (cic_collector_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (cic_collector_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (CIC_collector_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (CIC_collector_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_chipselect          (CIC_collector_0_avalon_master_chipselect),                                         //                          .chipselect
		.av_write               (CIC_collector_0_avalon_master_write),                                              //                          .write
		.av_writedata           (CIC_collector_0_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                             //               (terminated)
		.av_byteenable          (2'b11),                                                                            //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                                             //               (terminated)
		.av_read                (1'b0),                                                                             //               (terminated)
		.av_readdata            (),                                                                                 //               (terminated)
		.av_readdatavalid       (),                                                                                 //               (terminated)
		.av_lock                (1'b0),                                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                                             //               (terminated)
		.uav_clken              (),                                                                                 //               (terminated)
		.av_clken               (1'b1),                                                                             //               (terminated)
		.uav_response           (2'b00),                                                                            //               (terminated)
		.av_response            (),                                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (15),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (17),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) onchip_memory2_adc_a_s2_translator (
		.clk                    (pll_0_outclk0_clk),                                                                //                      clk.clk
		.reset                  (CIC_collector_0_reset_reset_bridge_in_reset_reset),                                //                    reset.reset
		.uav_address            (cic_collector_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (cic_collector_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (cic_collector_0_avalon_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (cic_collector_0_avalon_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (cic_collector_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (cic_collector_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (cic_collector_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (cic_collector_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (cic_collector_0_avalon_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (cic_collector_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (onchip_memory2_adc_a_s2_address),                                                  //      avalon_anti_slave_0.address
		.av_write               (onchip_memory2_adc_a_s2_write),                                                    //                         .write
		.av_readdata            (onchip_memory2_adc_a_s2_readdata),                                                 //                         .readdata
		.av_writedata           (onchip_memory2_adc_a_s2_writedata),                                                //                         .writedata
		.av_byteenable          (onchip_memory2_adc_a_s2_byteenable),                                               //                         .byteenable
		.av_chipselect          (onchip_memory2_adc_a_s2_chipselect),                                               //                         .chipselect
		.av_clken               (onchip_memory2_adc_a_s2_clken),                                                    //                         .clken
		.av_read                (),                                                                                 //              (terminated)
		.av_begintransfer       (),                                                                                 //              (terminated)
		.av_beginbursttransfer  (),                                                                                 //              (terminated)
		.av_burstcount          (),                                                                                 //              (terminated)
		.av_readdatavalid       (1'b0),                                                                             //              (terminated)
		.av_waitrequest         (1'b0),                                                                             //              (terminated)
		.av_writebyteenable     (),                                                                                 //              (terminated)
		.av_lock                (),                                                                                 //              (terminated)
		.uav_clken              (1'b0),                                                                             //              (terminated)
		.av_debugaccess         (),                                                                                 //              (terminated)
		.av_outputenable        (),                                                                                 //              (terminated)
		.uav_response           (),                                                                                 //              (terminated)
		.av_response            (2'b00),                                                                            //              (terminated)
		.uav_writeresponsevalid (),                                                                                 //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                              //              (terminated)
	);

endmodule
